# Generated by Django 3.0.1 on 2020-12-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201220_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='no_name', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='no_name', max_length=256),
        ),
    ]
