# Generated by Django 3.0.1 on 2020-12-22 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
        ('account', '0005_user_country_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='covid.country_code')),
            ],
        ),
    ]
