# Generated by Django 3.0.1 on 2020-12-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_countrylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylist',
            name='country',
            field=models.CharField(max_length=256),
        ),
    ]
